from datetime import time

horario_trabajo = {
                    "lunes": (time(8, 0), time(17, 0)),
                    "martes": (time(8, 0), time(17, 0)),
                    "miércoles": (time(8, 0), time(17, 0)),
                    "jueves": (time(8, 0), time(17, 0)),
                    "viernes": (time(8, 0), time(17, 0)),
                }




colaboradores = [
    {
        "idEmpleado": 1,
        "nombreCompleto": "Luis Rodríguez",
        "nombre_Puesto": "Desarrollador Backend",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/men/1.jpg",
        "primerNombreEmpleado": "Luis",
        "primerApellidoEmpleado": "Rodríguez"
    },
    {
        "idEmpleado": 2,
        "nombreCompleto": "María Pérez",
        "nombre_Puesto": "Diseñadora UX",
        "nombre_EstadoEmpleado": "VACACIONES",
        "imageUrl": "https://randomuser.me/api/portraits/women/2.jpg",
        "primerNombreEmpleado": "María",
        "primerApellidoEmpleado": "Pérez"
    },
    {
        "idEmpleado": 3,
        "nombreCompleto": "Carlos Jiménez",
        "nombre_Puesto": "Analista de Datos",
        "nombre_EstadoEmpleado": "LICENCIA",
        "imageUrl": "https://randomuser.me/api/portraits/men/3.jpg",
        "primerNombreEmpleado": "Carlos",
        "primerApellidoEmpleado": "Jiménez"
    },
    {
        "idEmpleado": 4,
        "nombreCompleto": "Ana Castillo",
        "nombre_Puesto": "Gerente de Proyectos",
        "nombre_EstadoEmpleado": "PERMISO",
        "imageUrl": "https://randomuser.me/api/portraits/women/4.jpg",
        "primerNombreEmpleado": "Ana",
        "primerApellidoEmpleado": "Castillo"
    },
    {
        "idEmpleado": 5,
        "nombreCompleto": "Pedro Martínez",
        "nombre_Puesto": "Contador",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/men/5.jpg",
        "primerNombreEmpleado": "Pedro",
        "primerApellidoEmpleado": "Martínez"
    },
    {
        "idEmpleado": 6,
        "nombreCompleto": "Laura Gómez",
        "nombre_Puesto": "Reclutadora",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/women/6.jpg",
        "primerNombreEmpleado": "Laura",
        "primerApellidoEmpleado": "Gómez"
    },
    {
        "idEmpleado": 7,
        "nombreCompleto": "Andrés Torres",
        "nombre_Puesto": "Soporte Técnico",
        "nombre_EstadoEmpleado": "PERMISO",
        "imageUrl": "https://randomuser.me/api/portraits/men/7.jpg",
        "primerNombreEmpleado": "Andrés",
        "primerApellidoEmpleado": "Torres"
    },
    {
        "idEmpleado": 8,
        "nombreCompleto": "Lucía Ramírez",
        "nombre_Puesto": "Abogada",
        "nombre_EstadoEmpleado": "LICENCIA",
        "imageUrl": "https://randomuser.me/api/portraits/women/8.jpg",
        "primerNombreEmpleado": "Lucía",
        "primerApellidoEmpleado": "Ramírez"
    },
    {
        "idEmpleado": 9,
        "nombreCompleto": "Jorge Herrera",
        "nombre_Puesto": "Auditor",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/men/9.jpg",
        "primerNombreEmpleado": "Jorge",
        "primerApellidoEmpleado": "Herrera"
    },
    {
        "idEmpleado": 10,
        "nombreCompleto": "Camila Díaz",
        "nombre_Puesto": "Coordinadora de Marketing",
        "nombre_EstadoEmpleado": "VACACIONES",
        "imageUrl": "https://randomuser.me/api/portraits/women/10.jpg",
        "primerNombreEmpleado": "Camila",
        "primerApellidoEmpleado": "Díaz"
    },
    {
        "idEmpleado": 11,
        "nombreCompleto": "Raúl Morales",
        "nombre_Puesto": "Administrador de Sistemas",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/men/11.jpg",
        "primerNombreEmpleado": "Raúl",
        "primerApellidoEmpleado": "Morales"
    },
    {
        "idEmpleado": 12,
        "nombreCompleto": "Valeria Soto",
        "nombre_Puesto": "Recepcionista",
        "nombre_EstadoEmpleado": "PERMISO",
        "imageUrl": "https://randomuser.me/api/portraits/women/12.jpg",
        "primerNombreEmpleado": "Valeria",
        "primerApellidoEmpleado": "Soto"
    },
    {
        "idEmpleado": 13,
        "nombreCompleto": "Manuel Cruz",
        "nombre_Puesto": "Director Financiero",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/men/13.jpg",
        "primerNombreEmpleado": "Manuel",
        "primerApellidoEmpleado": "Cruz"
    },
    {
        "idEmpleado": 14,
        "nombreCompleto": "Isabel Vargas",
        "nombre_Puesto": "Community Manager",
        "nombre_EstadoEmpleado": "LICENCIA",
        "imageUrl": "https://randomuser.me/api/portraits/women/14.jpg",
        "primerNombreEmpleado": "Isabel",
        "primerApellidoEmpleado": "Vargas"
    },
    {
        "idEmpleado": 15,
        "nombreCompleto": "David Peña",
        "nombre_Puesto": "Encargado de Logística",
        "nombre_EstadoEmpleado": "VACACIONES",
        "imageUrl": "https://randomuser.me/api/portraits/men/15.jpg",
        "primerNombreEmpleado": "David",
        "primerApellidoEmpleado": "Peña"
    },
    {
        "idEmpleado": 16,
        "nombreCompleto": "Sofía Navarro",
        "nombre_Puesto": "Diseñadora Gráfica",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/women/16.jpg",
        "primerNombreEmpleado": "Sofía",
        "primerApellidoEmpleado": "Navarro"
    },
    {
        "idEmpleado": 17,
        "nombreCompleto": "Tomás Rivas",
        "nombre_Puesto": "Mensajero",
        "nombre_EstadoEmpleado": "PERMISO",
        "imageUrl": "https://randomuser.me/api/portraits/men/17.jpg",
        "primerNombreEmpleado": "Tomás",
        "primerApellidoEmpleado": "Rivas"
    },
    {
        "idEmpleado": 18,
        "nombreCompleto": "Renata León",
        "nombre_Puesto": "Especialista en Seguridad",
        "nombre_EstadoEmpleado": "LICENCIA",
        "imageUrl": "https://randomuser.me/api/portraits/women/18.jpg",
        "primerNombreEmpleado": "Renata",
        "primerApellidoEmpleado": "León"
    },
    {
        "idEmpleado": 19,
        "nombreCompleto": "Mario Cordero",
        "nombre_Puesto": "Técnico de Mantenimiento",
        "nombre_EstadoEmpleado": "ACTIVO",
        "imageUrl": "https://randomuser.me/api/portraits/men/19.jpg",
        "primerNombreEmpleado": "Mario",
        "primerApellidoEmpleado": "Cordero"
    },
    {
        "idEmpleado": 20,
        "nombreCompleto": "Daniela Fuentes",
        "nombre_Puesto": "Asistente Administrativa",
        "nombre_EstadoEmpleado": "VACACIONES",
        "imageUrl": "https://randomuser.me/api/portraits/women/20.jpg",
        "primerNombreEmpleado": "Daniela",
        "primerApellidoEmpleado": "Fuentes"
    }
]


data = {
    "result": [
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 100000.00,
            "idDetallePeriodo": 624,
            "codigoPeriodo": "2024NEF13",
            "fechaInicioDetallePeriodo": "2024-07-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-07-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 1,
            "codigoConcepto": "SAL",
            "nombreConcepto": "Salario",
            "valor": 50000.00,
            "origen": 1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 100000.00,
            "idDetallePeriodo": 624,
            "codigoPeriodo": "2024NEF13",
            "fechaInicioDetallePeriodo": "2024-07-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-07-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "tipo_Concepto": 33,
            "nombre_Concepto": "AHorro",
            "idConcepto": 92,
            "codigoConcepto": "92",
            "nombreConcepto": "Prestamo Personal",
            "valor": 6250.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 143750.00,
            "balanceActual": 137500.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 100000.00,
            "idDetallePeriodo": 624,
            "codigoPeriodo": "2024NEF13",
            "fechaInicioDetallePeriodo": "2024-07-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-07-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 48,
            "codigoConcepto": "109",
            "nombreConcepto": "AFP",
            "valor": 2870.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 100000.00,
            "idDetallePeriodo": 624,
            "codigoPeriodo": "2024NEF13",
            "fechaInicioDetallePeriodo": "2024-07-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-07-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 49,
            "codigoConcepto": "110",
            "nombreConcepto": "SFS",
            "valor": 3040.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 100000.00,
            "idDetallePeriodo": 624,
            "codigoPeriodo": "2024NEF13",
            "fechaInicioDetallePeriodo": "2024-07-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-07-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 103,
            "codigoConcepto": "112",
            "nombreConcepto": "Descuento ISR",
            "valor": 11933.35,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 100000.00,
            "idDetallePeriodo": 624,
            "codigoPeriodo": "2024NEF13",
            "fechaInicioDetallePeriodo": "2024-07-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-07-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 108,
            "codigoConcepto": "018",
            "nombreConcepto": "Saldo a Favor x ISR",
            "valor": 1.00,
            "origen": 1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 626,
            "codigoPeriodo": "2024NEF15",
            "fechaInicioDetallePeriodo": "2024-08-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-08-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 1,
            "codigoConcepto": "SAL",
            "nombreConcepto": "Salario",
            "valor": 17500.00,
            "origen": 1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 626,
            "codigoPeriodo": "2024NEF15",
            "fechaInicioDetallePeriodo": "2024-08-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-08-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 123,
            "codigoConcepto": "123",
            "nombreConcepto": "Comisiones por Cobro",
            "valor": 2345.00,
            "origen": 1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 626,
            "codigoPeriodo": "2024NEF15",
            "fechaInicioDetallePeriodo": "2024-08-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-08-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 4,
            "codigoConcepto": "4",
            "nombreConcepto": "COMISION",
            "valor": 6786.00,
            "origen": 1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 626,
            "codigoPeriodo": "2024NEF15",
            "fechaInicioDetallePeriodo": "2024-08-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-08-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 92,
            "codigoConcepto": "92",
            "nombreConcepto": "Prestamo Personal",
            "valor": 6250.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 131250.00,
            "balanceActual": 125000.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 626,
            "codigoPeriodo": "2024NEF15",
            "fechaInicioDetallePeriodo": "2024-08-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-08-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 48,
            "codigoConcepto": "109",
            "nombreConcepto": "AFP",
            "valor": 764.31,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 626,
            "codigoPeriodo": "2024NEF15",
            "fechaInicioDetallePeriodo": "2024-08-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-08-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 49,
            "codigoConcepto": "110",
            "nombreConcepto": "SFS",
            "valor": 809.58,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "1",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 626,
            "codigoPeriodo": "2024NEF15",
            "fechaInicioDetallePeriodo": "2024-08-01T00:00:00",
            "fechaFinDetallePeriodo": "2024-08-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 103,
            "codigoConcepto": "112",
            "nombreConcepto": "Descuento ISR",
            "valor": 1474.92,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 696,
            "codigoPeriodo": "2025NEF01",
            "fechaInicioDetallePeriodo": "2025-01-01T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 1,
            "codigoConcepto": "SAL",
            "nombreConcepto": "Salario",
            "valor": 17500.00,
            "origen": 1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 696,
            "codigoPeriodo": "2025NEF01",
            "fechaInicioDetallePeriodo": "2025-01-01T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 85,
            "codigoConcepto": "85",
            "nombreConcepto": "Horas Extras al 35%",
            "valor": 6451.86,
            "origen": 1,
            "tarifaPago": 629.45,
            "cantidadHoras": 10.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 696,
            "codigoPeriodo": "2025NEF01",
            "fechaInicioDetallePeriodo": "2025-01-01T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 92,
            "codigoConcepto": "92",
            "nombreConcepto": "Prestamo Personal",
            "valor": 6250.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 131250.00,
            "balanceActual": 125000.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 696,
            "codigoPeriodo": "2025NEF01",
            "fechaInicioDetallePeriodo": "2025-01-01T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 48,
            "codigoConcepto": "109",
            "nombreConcepto": "AFP",
            "valor": 502.25,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 696,
            "codigoPeriodo": "2025NEF01",
            "fechaInicioDetallePeriodo": "2025-01-01T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 49,
            "codigoConcepto": "110",
            "nombreConcepto": "SFS",
            "valor": 532.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 696,
            "codigoPeriodo": "2025NEF01",
            "fechaInicioDetallePeriodo": "2025-01-01T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-15T00:00:00",
            "intervaloPeriodo": 1,
            "descripcionPeriodo": "",
            "idConcepto": 103,
            "codigoConcepto": "112",
            "nombreConcepto": "Descuento ISR",
            "valor": 704.75,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 697,
            "codigoPeriodo": "2025NEF02",
            "fechaInicioDetallePeriodo": "2025-01-16T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-31T00:00:00",
            "intervaloPeriodo": 2,
            "descripcionPeriodo": "",
            "idConcepto": 1,
            "codigoConcepto": "SAL",
            "nombreConcepto": "Salario",
            "valor": 17500.00,
            "origen": 1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 697,
            "codigoPeriodo": "2025NEF02",
            "fechaInicioDetallePeriodo": "2025-01-16T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-31T00:00:00",
            "intervaloPeriodo": 2,
            "descripcionPeriodo": "",
            "idConcepto": 92,
            "codigoConcepto": "92",
            "nombreConcepto": "Prestamo Personal",
            "valor": 6250.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 125000.00,
            "balanceActual": 118750.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 697,
            "codigoPeriodo": "2025NEF02",
            "fechaInicioDetallePeriodo": "2025-01-16T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-31T00:00:00",
            "intervaloPeriodo": 2,
            "descripcionPeriodo": "",
            "idConcepto": 48,
            "codigoConcepto": "109",
            "nombreConcepto": "AFP",
            "valor": 502.25,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        },
        {
            "idEmpleado": 25,
            "codigoEmpleado": "25",
            "primerNombre": "Colt",
            "segundoNombre": "Pascale",
            "primerApellido": "Reilly",
            "segundoApellido": "Wilder",
            "identificacion": "22222222222",
            "idBanco": 1,
            "nombreBanco": "Banco Popular",
            "numeroCuenta": "11111111",
            "idNomina": 115,
            "codigoNomina": "NEF",
            "nombreNomina": "Nómina Empleados Fijos ARQ",
            "salario": 35000.00,
            "idDetallePeriodo": 697,
            "codigoPeriodo": "2025NEF02",
            "fechaInicioDetallePeriodo": "2025-01-16T00:00:00",
            "fechaFinDetallePeriodo": "2025-01-31T00:00:00",
            "intervaloPeriodo": 2,
            "descripcionPeriodo": "",
            "idConcepto": 49,
            "codigoConcepto": "110",
            "nombreConcepto": "SFS",
            "valor": 532.00,
            "origen": -1,
            "tarifaPago": 0.00,
            "cantidadHoras": 0.00,
            "idCompania": 3,
            "nombreCompania": "Mallén Veterinaria S. A.",
            "idDepartamento": 117,
            "nombreDepartamento": "Diseño industrial",
            "idPuesto": 107,
            "nombrePuesto": "Gerente de Logistica",
            "idSucursal": 11,
            "nombreSucursal": "Banesco",
            "balanceAnterior": 0.00,
            "balanceActual": 0.00,
            "correo": "epaniagua@camsoft.com.do",
            "idFormaPago": 1,
            "nombreFormaPago": "Transferencia",
            "idioma": "es-DO"
        }
    ],
    "extended": {
        "recordCount": 0,
        "largeProcessResult": None
    }
}


cumpleanos = [
  {
    "nombre": "Juan Pérez",
    "codigo": "EMP001",
    "fecha_cumpleanos": "1990-04-15"
  },
  {
    "nombre": "María Gómez",
    "codigo": "EMP002",
    "fecha_cumpleanos": "1985-04-22"
  },
  {
    "nombre": "Carlos Ramírez",
    "codigo": "EMP003",
    "fecha_cumpleanos": "1992-04-30"
  }
]


promociones = [
  {
    "nombre": "Ana Rodríguez",
    "codigo": "EMP101",
    "fecha_promocion": "2025-04-05",
    "puesto_anterior": "Analista Junior",
    "nuevo_puesto": "Analista Senior",
    "descripcion_nuevo_puesto": "Encargado de liderar proyectos de análisis de datos y reportes avanzados."
  },
  {
    "nombre": "Luis Fernández",
    "codigo": "EMP102",
    "fecha_promocion": "2025-04-12",
    "puesto_anterior": "Asistente Administrativo",
    "nuevo_puesto": "Coordinador Administrativo",
    "descripcion_nuevo_puesto": "Responsable de coordinar procesos administrativos y supervisar equipo de soporte."
  },
  {
    "nombre": "Elena Castro",
    "codigo": "EMP103",
    "fecha_promocion": "2025-04-20",
    "puesto_anterior": "Desarrollador Junior",
    "nuevo_puesto": "Desarrollador Senior",
    "descripcion_nuevo_puesto": "Desarrolla soluciones avanzadas de software y lidera iniciativas tecnológicas."
  }
]

